
[functions.calculate-coro]
enabled = true
verify_jwt = true
import_map = "./functions/calculate-coro/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/calculate-coro/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/calculate-coro/*.html" ]

[functions.calculate-ada]
enabled = true
verify_jwt = true
import_map = "./functions/calculate-ada/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/calculate-ada/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/calculate-ada/*.html" ]

[functions.calculate-yard]
enabled = true
verify_jwt = true
import_map = "./functions/calculate-yard/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/calculate-yard/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/calculate-yard/*.html" ]

[functions.calculate-acm]
enabled = true
verify_jwt = true
import_map = "./functions/calculate-acm/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/calculate-acm/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/calculate-acm/*.html" ]

[functions.calculate-acrylic]
enabled = true
verify_jwt = true
import_map = "./functions/calculate-acrylic/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/calculate-acrylic/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/calculate-acrylic/*.html" ]

[functions.calculate-banner]
enabled = true
verify_jwt = true
import_map = "./functions/calculate-banner/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/calculate-banner/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/calculate-banner/*.html" ]

[functions.calculate-decal]
enabled = true
verify_jwt = true
import_map = "./functions/calculate-decal/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/calculate-decal/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/calculate-decal/*.html" ]

[functions.calculate-wrap]
enabled = true
verify_jwt = true
import_map = "./functions/calculate-wrap/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/calculate-wrap/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/calculate-wrap/*.html" ]

[functions.calculate-pvc]
enabled = true
verify_jwt = true
import_map = "./functions/calculate-pvc/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/calculate-pvc/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/calculate-pvc/*.html" ]

[functions.calculate-foam]
enabled = true
verify_jwt = true
import_map = "./functions/calculate-foam/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/calculate-foam/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/calculate-foam/*.html" ]

[functions.calculate-cut]
enabled = true
verify_jwt = true
import_map = "./functions/calculate-cut/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/calculate-cut/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/calculate-cut/*.html" ]

[functions.calculate-wall]
enabled = true
verify_jwt = true
import_map = "./functions/calculate-wall/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/calculate-wall/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/calculate-wall/*.html" ]

[functions.calculate-nameplate]
enabled = true
verify_jwt = true
import_map = "./functions/calculate-nameplate/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/calculate-nameplate/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/calculate-nameplate/*.html" ]

[functions.calculate-post-panel]
enabled = true
verify_jwt = true
import_map = "./functions/calculate-post-panel/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/calculate-post-panel/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/calculate-post-panel/*.html" ]
