

import React, { useEffect, useState } from 'react';
import { FontLoader } from 'three/examples/jsm/loaders/FontLoader.js';
import * as THREE from 'three';
import { X, Copy, Check } from 'lucide-react';
import { FONT_LIBRARY } from '../../constants';

interface Props {
  fontName: string;
  onClose: () => void;
}

export const FontCalibratorModal: React.FC<Props> = ({ fontName, onClose }) => {
  const [loading, setLoading] = useState(true);
  const [outputCode, setOutputCode] = useState('');
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fontData = FONT_LIBRARY[fontName];
    if (!fontData) {
      setError(`Font "${fontName}" not found in registry.`);
      setLoading(false);
      return;
    }

    // Determine if we are loading from URL or Object
    const loadFont = () => {
        try {
            const loader = new FontLoader();
            // If font property is an object, parse it directly
            if (typeof fontData.font === 'object') {
                const font = loader.parse(fontData.font as any);
                processFont(font);
            } else if (typeof fontData.font === 'string') {
                 // It's a URL
                 loader.load(
                    fontData.font,
                    (font) => processFont(font),
                    undefined,
                    (err) => {
                        setError("Failed to load font file from URL.");
                        setLoading(false);
                    }
                 );
            } else if ((fontData as any).url) {
                // Fallback to legacy URL property
                 loader.load(
                    (fontData as any).url,
                    (font) => processFont(font),
                    undefined,
                    (err) => {
                        setError("Failed to load font file from legacy URL.");
                        setLoading(false);
                    }
                 );
            } else {
                setError("No valid font source found.");
                setLoading(false);
            }
        } catch (e) {
            setError("Error initializing font loader: " + e);
            setLoading(false);
        }
    };

    const processFont = (font: any) => {
        try {
          const charsToMeasure = [
            'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z',
            '0','1','2','3','4','5','6','7','8','9',
            ' ', '.', ',', '-', '!'
          ];

          const ratios: Record<string, number> = {};
          let totalRatio = 0;
          let count = 0;

          // Perform measurements
          charsToMeasure.forEach(char => {
             const shapes = font.generateShapes(char, 100); // Height 100 arbitrary
             const geometry = new THREE.ShapeGeometry(shapes);
             geometry.computeBoundingBox();
             
             if (geometry.boundingBox) {
                 const w = geometry.boundingBox.max.x - geometry.boundingBox.min.x;
                 const h = 100; // Based on input size
                 const ratio = Number((w / h).toFixed(2));
                 ratios[char] = ratio;
                 
                 // Exclude narrow punctuation/spaces from default average calculation for better accuracy
                 if (![' ', '.', ',', 'I', '1', '!'].includes(char)) {
                    totalRatio += ratio;
                    count++;
                 }
             }
          });

          const defaultRatio = count > 0 ? Number((totalRatio / count).toFixed(2)) : 0.6;

          // Generate Code String
          const code = `
import { CharacterRatios } from './types';

// Metrics for: ${fontName}
// Generated by SignFabricator OS Calibrator
const RATIOS: CharacterRatios = {
    // Uppercase
${charsToMeasure.slice(0, 26).map(c => `    '${c}': ${ratios[c].toFixed(2)}`).join(', ')},

    // Numbers
${charsToMeasure.slice(26, 36).map(c => `    '${c}': ${ratios[c].toFixed(2)}`).join(', ')},

    // Punctuation
${charsToMeasure.slice(36).map(c => `    '${c}': ${ratios[c].toFixed(2)}`).join(', ')}
};

export const ${fontName.replace(/\s/g, '').replace(/[^a-zA-Z0-9]/g, '')}Metrics = {
    defaultRatio: ${defaultRatio},
    chars: RATIOS
};
`;
          setOutputCode(code.trim());
          setLoading(false);
        } catch (err) {
          console.error(err);
          setError("Error calculating metrics geometry.");
          setLoading(false);
        }
    };

    loadFont();

  }, [fontName]);

  const handleCopy = () => {
    navigator.clipboard.writeText(outputCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4">
       <div className="bg-slate-900 border border-slate-700 rounded-xl shadow-2xl w-full max-w-2xl flex flex-col max-h-[90vh]">
          
          <div className="flex justify-between items-center p-4 border-b border-slate-700">
             <h3 className="text-lg font-bold text-white flex items-center gap-2">
               Calibrate Font: <span className="text-blue-400">{fontName}</span>
             </h3>
             <button onClick={onClose} className="text-slate-400 hover:text-white transition-colors"><X size={20}/></button>
          </div>

          <div className="flex-1 overflow-auto p-0 relative group">
             {loading ? (
               <div className="flex flex-col items-center justify-center h-64 gap-3">
                 <div className="w-8 h-8 border-4 border-blue-500 border-t-transparent rounded-full animate-spin"></div>
                 <p className="text-slate-400 animate-pulse">Measuring geometry...</p>
               </div>
             ) : error ? (
               <div className="p-8 text-center text-red-400">
                 <p>{error}</p>
               </div>
             ) : (
               <div className="relative">
                 <button 
                   onClick={handleCopy}
                   className="absolute top-4 right-4 bg-slate-800 hover:bg-slate-700 text-slate-200 px-3 py-1.5 rounded border border-slate-600 flex items-center gap-2 text-xs font-medium transition-all shadow-lg"
                 >
                   {copied ? <Check size={14} className="text-emerald-400"/> : <Copy size={14}/>}
                   {copied ? 'Copied!' : 'Copy Code'}
                 </button>
                 <pre className="p-6 bg-slate-950 text-emerald-400 font-mono text-xs overflow-auto custom-scrollbar leading-relaxed selection:bg-blue-900 selection:text-white">
                    {outputCode}
                 </pre>
               </div>
             )}
          </div>

          <div className="p-4 bg-slate-800 border-t border-slate-700 text-xs text-slate-400 flex justify-between items-center">
             <span>Usage: Paste this content into a new file in <code>data/fonts/</code> and import it in <code>index.ts</code>.</span>
             <button onClick={onClose} className="bg-slate-700 hover:bg-slate-600 text-white px-4 py-2 rounded transition-colors">Done</button>
          </div>
       </div>
    </div>
  );
};